version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.432-alpine-jdk21
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000 

volumes:
  jenkins-data: 
